2020-03-23 17:39:46,014 - Logs - INFO - 【**********************TEST START**********************】
2020-03-23 17:39:46,015 - Logs - DEBUG - 浏览器驱动为:F:\automation_git\FormTalk\WebTEST\main\drivers\chromedriver.exe
2020-03-23 17:39:51,180 - Logs - INFO - 执行case:【正确登录】用例
2020-03-23 17:39:58,796 - main.pages.LoginPage - DEBUG - 使用用户：[18502827849/1234561]进行登录 
2020-03-23 17:40:00,164 - main.pages.LoginPage - DEBUG - 加载中... 
2020-03-23 17:40:02,449 - main.pages.LoginPage - DEBUG - 加载中... 
2020-03-23 17:40:12,561 - main.pages.LoginPage - ERROR - 登录失败
2020-03-23 17:40:17,673 - main.pages.MainPage - DEBUG - Log_Test
2020-03-23 17:40:17,674 - main.pages.LoginPage - ERROR - unexpectedly None : 登录失败，未找到【首页】标题
2020-03-23 17:40:17,674 - main.pages.LoginPage - ERROR - Traceback (most recent call last):
  File "F:\automation_git\FormTalk\WebTEST\main\commom\tools\ExceptionHandling.py", line 49, in AssertIsNotNone
    self.assertIsNotNone(first,er_msg)
  File "E:\Program_Files\python3\lib\unittest\case.py", line 1269, in assertIsNotNone
    self.fail(self._formatMessage(msg, standardMsg))
  File "E:\Program_Files\python3\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: unexpectedly None : 登录失败，未找到【首页】标题

2020-03-23 17:40:19,801 - Logs - DEBUG - 浏览器驱动为:F:\automation_git\FormTalk\WebTEST\main\drivers\chromedriver.exe
2020-03-23 17:40:24,945 - Logs - INFO - 执行case:【用户名、密码错误】用例
2020-03-23 17:40:33,229 - main.pages.LoginPage - DEBUG - 使用用户：[18502827848/1234567]进行登录 
2020-03-23 17:40:34,581 - main.pages.LoginPage - DEBUG - 加载中... 
2020-03-23 17:40:36,865 - main.pages.LoginPage - DEBUG - 加载中... 
2020-03-23 17:40:46,974 - main.pages.LoginPage - ERROR - 登录失败
2020-03-23 17:40:47,095 - main.pages.MainPage - DEBUG - Log_Test
2020-03-23 17:40:49,212 - Logs - INFO - 【**********************TEST END**********************】
